update documention
serqlane/serqlane pull request #59
Opened 2023-12-27 05:23 UTC by SolarWolf-Code

Update various files to allow others to easily jump into developing. Would be nice to start on some documentation as well, such as a md file containing things like types, syntax, conventions, etc.. We should also consider adding templates for issues

2023-12-27 13:34 UTC, StarrFox approved these changes
current files look good to me

2023-12-27 13:35 UTC, StarrFox commented
for documentation what do you think about using mkDocs

2023-12-27 17:48 UTC, SolarWolf-Code commented
> for documentation what do you think about using mkDocs

I think mkDocs works well. I'll get started on some basic documentation and we can fill in the blanks where necessary

2023-12-27 18:08 UTC, StarrFox commented
https://github.com/serqlane/serqlane/commit/1d86647f7cc261e882adeafc6b6f1b8008966bcb fixes the required check issue

2023-12-27 20:06 UTC, SolarWolf-Code commented
I think the documentation is pretty decent for now. With the exception on the unary operators section (https://github.com/serqlane/serqlane/issues/61), everything _should_ be covered

![image](https://github.com/serqlane/serqlane/assets/54452723/41f51a66-e519-4a24-93c1-ee1434919e9f)

2023-12-28 10:56 UTC, SirOlaf commented
I would prefer to generate docs from exported symbols

2024-01-05 01:35 UTC, StarrFox commented
this looks ready to merge to me

2024-01-08 05:45 UTC, SolarWolf-Code commented
If we want to hold off on Github Pages (if we intend to host docs here) I'd consider this done. Otherwise, I can add the pages bit and we can merge this

2024-01-08 14:49 UTC, StarrFox commented
what's the reason to not do github pages?

2024-01-08 14:56 UTC, StarrFox requested changes

2024-01-08 14:56 UTC, StarrFox commented on docs/introduction.md
> +Now that you have serqlane installed, you can check out the [Writing Serqlane](writing-serqlane.md) to learn more about the language.
the `the` here is unneeded

2024-01-08 14:56 UTC, StarrFox commented on docs/writing-serqlane.md
> +To use an arithmetic operator, use the operator between two values. For example:
`values` should maybe be `expressions`

2024-01-08 14:56 UTC, StarrFox commented on docs/writing-serqlane.md
> +fn add(x: int64, y: int64) -> int64 {
this needs a `pub` before to mark it as public

2024-01-08 14:56 UTC, StarrFox commented on docs/writing-serqlane.md
> +fn pub add(x: int64, y: int64) -> int64 {
this should be `pub fn` instead of `fn pub`

2024-01-08 16:06 UTC, SolarWolf-Code commented
> what's the reason to not do github pages?

I personally didn't think there was a reason against it but I felt I should leave it open. I'll create a workflow that publishes it to a gh-pages branch.

Let me also address the typos you brought up 😼

2024-01-08 17:15 UTC, SolarWolf-Code commented
When this PR is merged. We'll need to add the docs site to GitHub Pages:

Head to settings:  
![image](https://github.com/serqlane/serqlane/assets/54452723/c59c000c-6a28-469d-b36a-fe8f30136118)  

Go to pages section:
![image](https://github.com/serqlane/serqlane/assets/54452723/d82c08c0-6e9a-4b01-8ee5-f5b06f1f8451)  

Update the branch to `gh-pages` and custom domain to `docs.serqlane.org`:  
![image](https://github.com/serqlane/serqlane/assets/54452723/411b3e68-b63e-4609-8515-566358a8ddae)  


After that is set I will update DNS records to include a CNAME for docs subdomain to point towards `serqlane.github.io` and we should be set

2024-01-09 18:18 UTC, StarrFox approved these changes

2024-01-09 18:19 UTC, merged